name: Build and test
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v3
      -uses: actions/setup-checkout@v3
       with:
        node-version: 18
      -run: npm ci
      -run: npm build
      -run: npm run test:integration
      -run: npm run test:e2e
      -uses: actions/upload-artivate@v3
       with: 
        name: e2e-videos
        path: cypress/videos/

